from __future__ import annotations

from datetime import datetime
from pathlib import Path

from edison.core.composition.headers import build_generated_header
from edison.core.config import ConfigManager


def _load_header_template(cfg_mgr: ConfigManager) -> str:
    cfg = cfg_mgr.load_config(validate=False)
    header_template = (cfg.get("composition") or {}).get("generatedFileHeader") or ""
    assert header_template.strip(), "composition.generatedFileHeader must be configured"
    return header_template.strip()


def test_constitution_templates_embed_generated_header() -> None:
    cfg_mgr = ConfigManager()
    header_template = _load_header_template(cfg_mgr)

    templates_dir = Path("src/edison/data/constitutions")
    templates = sorted(templates_dir.glob("*-base.md"))
    assert templates, "expected constitution templates to exist"

    for path in templates:
        content = path.read_text(encoding="utf-8")
        assert header_template in content, f"missing header in {path}"


def test_header_builder_renders_configured_values() -> None:
    cfg_mgr = ConfigManager()
    cfg = cfg_mgr.load_config(validate=False)
    version = (cfg.get("edison") or {}).get("version")
    ts = datetime(2023, 1, 2, 3, 4, 5)

    header = build_generated_header("rosters.available_agents", config=cfg_mgr, generated_at=ts)

    assert "AUTO-GENERATED FILE - DO NOT EDIT MANUALLY" in header
    assert f"Generated by: Edison Framework v{version}" in header
    assert "Template: rosters.available_agents" in header
    assert f"Generated at: {ts.isoformat()}" in header
    assert header.strip().startswith("<!--")
    assert header.strip().endswith("-->")
