from __future__ import annotations

from pathlib import Path
import os

from edison.core.utils.subprocess import run_with_timeout


class TestPalPrompts:
    def test_generic_prompts_exist(self, isolated_project_env: Path):
        """Pal prompt artifacts should be generated by composition (no extra workflow footer required)."""
        repo_root = isolated_project_env

        env = os.environ.copy()
        env["AGENTS_PROJECT_ROOT"] = str(repo_root)

        result = run_with_timeout(
            ["uv", "run", "edison", "compose", "all"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            env=env,
        )
        assert result.returncode == 0, (
            f"compose failed with exit code {result.returncode}\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}"
        )

        pal_prompts_dir = (
            repo_root / ".pal" / "conf" / "systemprompts" / "clink" / "project"
        )
        assert pal_prompts_dir.exists(), "Pal prompts directory not found after compose"

        prompt_path = pal_prompts_dir / "default.txt"
        assert prompt_path.exists(), "default.txt not found after compose"

        content = prompt_path.read_text(encoding="utf-8")
        assert content.strip(), "default.txt is empty"

    def test_default_prompt_is_stable_markdownish_text(self, isolated_project_env: Path):
        """Smoke check: composed Pal prompt looks like a composed Edison artifact."""
        repo_root = isolated_project_env

        env = os.environ.copy()
        env["AGENTS_PROJECT_ROOT"] = str(repo_root)

        result = run_with_timeout(
            ["uv", "run", "edison", "compose", "all"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            env=env,
        )
        assert result.returncode == 0, (
            f"compose failed with exit code {result.returncode}\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}"
        )

        pal_prompts_dir = (
            repo_root / ".pal" / "conf" / "systemprompts" / "clink" / "project"
        )

        assert pal_prompts_dir.exists(), "Pal prompts directory not found after compose"

        content = (pal_prompts_dir / "default.txt").read_text(encoding="utf-8")
        # Header is composed by PalComposerMixin; keep this as a loose sanity check.
        assert "=== Edison / Pal MCP Prompt ===" in content
