from __future__ import annotations

from pathlib import Path
import subprocess
import sys

import pytest


CORE = Path(__file__).resolve().parents[3]
ROOT = CORE.parents[1]
if str(CORE) not in sys.path:

from edison.core.composition import CompositionEngine 
from edison.core.utils.subprocess import run_with_timeout


class TestClaudeOrchestrator:
    def test_claude_brief_exists_with_key_sections(self) -> None:
        """Ensure the core Claude orchestrator brief exists and is well-formed."""
        repo_root = ROOT

        claude_brief = (
            repo_root / ".edison" / "packs" / "clients" / "claude" / "CLAUDE.md"
        )
        assert claude_brief.exists(), (
            "Missing .edison/packs/clients/claude/CLAUDE.md "
            "- Claude orchestrator brief must exist"
        )

        content = claude_brief.read_text(encoding="utf-8")
        assert "# Claude Orchestrator Brief" in content
        assert "Decision Scope" in content
        assert "Delegation Priority Chain" in content
        assert "Workflow Loop" in content
        assert "RULE.DELEGATION.PRIORITY_CHAIN" in content

    def test_claude_md_at_root_references_orchestrator_brief(self) -> None:
        """Verify .claude/CLAUDE.md references the orchestrator brief."""
        repo_root = ROOT

        claude_md = repo_root / ".claude" / "CLAUDE.md"
        assert claude_md.exists(), "Missing .claude/CLAUDE.md"

        content = claude_md.read_text(encoding="utf-8")
        if "{{include:.edison/packs/clients/claude/CLAUDE.md}}" in content:
            # Template form: include-based orchestrator
            assert "{{include:.edison/packs/clients/claude/CLAUDE.md}}" in content
        else:
            # Generated form: fully expanded orchestrator
            assert "# Claude Orchestrator Brief" in content

    @pytest.mark.integration
    def test_compose_claude_orchestrator_generates_output(self, tmp_path: Path) -> None:
        """End-to-end generation of Claude orchestrator into a target directory."""
        engine = CompositionEngine(repo_root=ROOT)

        out_dir = tmp_path / "claude-out"
        output_file = engine.compose_claude_orchestrator(out_dir)

        assert output_file.exists(), "compose_claude_orchestrator() must write CLAUDE.md"
        assert output_file.name == "CLAUDE.md"

        content = output_file.read_text(encoding="utf-8")
        assert content.startswith("# Claude Code Orchestrator")
        assert "<!-- GENERATED - DO NOT EDIT -->" in content
        # Core brief should be fully expanded into the generated orchestrator
        assert "# Claude Orchestrator Brief" in content
        assert "Delegation Priority Chain" in content

    @pytest.mark.integration
    def test_cli_compose_claude_flag_generates_root_orchestrator(self) -> None:
        """scripts/prompts/compose --claude should generate .claude/CLAUDE.md."""
        compose_script = (
            ROOT / ".edison" / "core" / "scripts" / "prompts" / "compose"
        )
        assert compose_script.exists(), "Missing compose script at expected path"

        result = run_with_timeout(
            [sys.executable, str(compose_script), "--claude"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )

        assert (
            result.returncode == 0
        ), f"compose --claude failed: {result.stderr or result.stdout}"

        claude_md = ROOT / ".claude" / "CLAUDE.md"
        assert claude_md.exists(), ".claude/CLAUDE.md should be generated by compose --claude"

        content = claude_md.read_text(encoding="utf-8")
        assert "# Claude Code Orchestrator" in content
        assert "# Claude Orchestrator Brief" in content